# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Rope Yarns
tagline:          'Dublin'
description:      'Learn the ropes you need!'
url:              https://ropeyarns.com
baseurl:          ""

author:
  name:           ''
  url:            "https://ropeyarns.com"

#paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/ropeyarns.github.io
